[workspace]
authors = ["Justus Magin <keewis@posteo.de>"]
channels = ["conda-forge"]
name = "regridding-ecosystem"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
xarray = ">=2025.3.1,<2026"
xesmf = ">=0.8.8,<0.9"
xdggs = ">=0.2.0,<0.3"
matplotlib = ">=3.10.1,<4"
netcdf4 = ">=1.7.2,<2"
h5netcdf = ">=1.6.1,<2"
scipy = ">=1.15.2,<2"
zarr = ">=3.0.6,<4"
jupyterlab = ">=4.4.0,<5"
jupyterlab_code_formatter = ">=3.0.2,<4"
jupyter-resource-usage = ">=1.1.1,<2"
black = ">=25.1.0,<26"
isort = ">=6.0.1,<7"
ruff = ">=0.11.5,<0.12"
jedi-language-server = ">=0.44.0,<0.45"
dask = ">=2025.3.0,<2026"
distributed = ">=2025.3.0,<2026"
dask-labextension = ">=7.0.0,<8"
cartopy = ">=0.24.0,<0.25"
